# Generated by Django 3.2 on 2024-04-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userType',
            field=models.CharField(choices=[('1', 'House Owner'), ('2', 'Renter')], default=2, max_length=10),
        ),
    ]
