# Generated by Django 3.2 on 2024-04-07 12:00

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='house_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='I want to rent this apartment or building', max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('house_name', models.CharField(max_length=200, null=True)),
                ('house_type', models.CharField(max_length=200, null=True)),
                ('house_area', models.IntegerField(default=800)),
                ('description', models.TextField()),
                ('is_parking', models.BooleanField(default=True)),
                ('total_bedrooms', models.IntegerField(default=0)),
                ('total_bathrooms', models.IntegerField(default=0)),
                ('floor_no', models.IntegerField(default=0)),
                ('monthly_maintenance_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('monthly_rent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('advance_rent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('thumbnail', models.ImageField(upload_to='house_thumbnails/')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='App_Rental.city')),
                ('images', models.ManyToManyField(blank=True, related_name='houses', to='App_Rental.HouseImage')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
