# Generated by Django 3.2 on 2024-04-07 14:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
