# Generated by Django 3.2 on 2024-04-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Rental', '0002_alter_house_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='house_name',
            field=models.CharField(choices=[('1', 'Apartment'), ('2', 'Building')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='house',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
