# Generated by Django 3.2 on 2024-04-07 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Rental', '0004_remove_house_monthly_maintenance_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='advance_rent',
        ),
        migrations.RemoveField(
            model_name='house',
            name='thumbnail',
        ),
    ]
