# Generated by Django 3.2 on 2024-04-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Rental', '0007_house_advacne_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
