# Generated by Django 3.2 on 2024-04-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Rental', '0008_house_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='is_reject',
            field=models.BooleanField(default=False),
        ),
    ]
