# Generated by Django 3.2 on 2024-04-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Rental', '0009_house_is_reject'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='is_rented',
            field=models.BooleanField(default=False),
        ),
    ]
