# Generated by Django 3.2 on 2024-04-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Rental', '0010_house_is_rented'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
