# Generated by Django 3.2 on 2024-04-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Rental', '0011_house_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='house_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_type',
            field=models.CharField(choices=[('1', 'Apartment'), ('2', 'Building')], default='1', max_length=10),
        ),
    ]
