# Generated by Django 3.2 on 2024-04-10 10:48

import App_Rental.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Rental', '0014_houserent'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='rent_from',
            field=models.DateField(default=App_Rental.models.House.next_month_first_day),
        ),
    ]
